title: "Technoecology"
description: "A dialogue between mind, nature, and technology."
baseurl: "" # Lascia vuoto per GitHub Pages
url: "https://frescodicredito.github.io"
markdown: kramdown
theme: minima
permalink: pretty

collections:
  pages:
    output: true
