# Configurazione base
title: "Technoecology"
description: "Exploring the intersections of mind, nature, and technology."
baseurl: "" # Lascia vuoto per GitHub Pages
url: "https://frescodicredito.github.io"

# Navigazione aggiunta per il menu
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about.html

# Informazioni autore
author:
  name: "Your Name"
  email: "youremail@example.com"

# Tema personalizzato
theme: jekyll-theme-slate

# Markdown e opzioni Kramdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Permalink
permalink: pretty

# Layout predefiniti
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Paginazione (facoltativo)
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# Esclusione file non necessari
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
